services:
  - type: web
    name: hook-boost-3-0
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
    autoDeploy: true 